### ISSUE TITLE
click error

### ISSUE THREAD

**Issue by WarningDarbe** [Just-Msv/Tokens-Gen#5]
error: TypeError: Cannot read property 'click' of null

error line:   await i.click();

what should I do

**Comment by limjame28** [comment]
i got the same error hmm

**Comment by Haris123346** [comment]
> I have fixed this by changing line #70 to the following:
> 
> `var i = await page.$('[aria-label="'+name+'"]');`

when i try this it stays on the discord page and nothing happens

**Comment by Just-Msv** [comment]
Try in Vs not in replit
